### ISSUE TITLE
backend fullstack

### ISSUE THREAD

**Issue by rsbegue** [hurbcom/vagas#9]
# Raphael Sbegue Garcia

|   |   |   |
|---|---|--:|
| Rua Manoel Lopes da Cunha, 77 |   | rsbegue@gmail.com |
| Vila Mangalot, São Paulo  |    | @rsbegue |
| São Paulo, 05132-070 |    | https://www.linkedin.com/in/raphaelsbegue/ |
| Brasil |    | +55 11 95179-1346 |

## Educação

- **Pós-Graduação de Gestão Estratégica de Negócios**
 ```
  2018 ~ - UniCesumar
  Status: matrícula trancada
 ```

- **Tecnologo em Desenvolvimento Web**
 ```
  2004-2006 - IBTA - Instituto Brasileiro de Tecnologia Avançada
  Título do trabalho final: Viaje Fácil - Portal de Compras de Passagens Online para transporte rodoviário
 ```

## Experiência

**2016/2018 - Planetun Services**
```
Papel: Web Full Stack Developer
* Desenvolvedor Full Stack focado em SaaS e soluções recorrentes de assinatura, comissões e splits de pagamentos para produtos digitais na empresa;
* Iniciar modelos de treinamento em Machine Learning, com Python, para identificar fraudes em pesquisas de seguros de imagens e realizar validações em processos de triagem automatizada [link](https://www.grupoplanetun.com.br/chega-ao-mercado-solucao-antifraude-inedita-para-seguradoras/);
* Participação ativa no desenvolvimento de novos produtos voltados ao público [link](https://www.grupoplanetun.com.br/insurtech-lanca-quatro-solucoes-inovadoras/);
```

**2012/2016 - Proweb Soluções**
```
Papel: Web Full Stack Developer / Product Owner
* Product Manager do SINPRO e SINPROWEB. Ambos softwares SaaS para monitoramento de peças e acessórios nas principais montadoras do Brasil;
```

**2010/2012 - sLoad**
```
Papel: Web Full Stack Developer / Product Manager
Projetos em: www.sload.com.br
* Part-time entre 2010 e 2011;
* Full time a partir de 2011;
* Full Stack Developer focado em SaaS e soluções em pagamentos recorrente, comissões e splits para produtos digitais;
* Credenciamento no programa de Parceiro Google conseguindo o selo por 2 anos consecutivos;
```

**2011/2011 – Eicon Controles Inteligentes**
```
Papel: Web Full Stack Developer
* Manutenção e desenvolvimento de novos módulos na ferramenta de emissão de NFs para prefeitura de Fortaleza-CE;
* Membro da célula de novos projetos;
* Desenvolvimento de plataforma de Chat com Node.js e WebSockets;
* Apoio a equipe de NOC para novas implementações de segurança na aplicação e ambiente;
```

**2010/2011 – Goorila E-Soluções em Internet (Lightcomm Group)**
```
Papel: Desenvolvedor Sênior e líder técnico de célula de novos projetos.
* Coordenador do projeto TIM Revenda de Celulares (Flex 4.5 + ZendAMF + MySQL ); 
* Coordenador do projeto OI Indicadores (Flex 4.5 + ZendAMF + MySQL);
```

**2009/2010 – Lightcomm Group**
```
Papel: Adobe Flex Developer, Web Full Stack Developer
Projetos para Tim, Claro e Oi
* Projeto SFA / Hotsite OI Internet (Flex 3 + ZendAMF + PostgreSQL 8.2); 
* Projeto Claro Televendas (Flex 3.5 + ZendAMF + PostgreSQL 8.4);
```

**2006/2009 – UptoDate**
```
Papel: Adobe Coldfusion Developer e Rich Internet Applications Developer Projetos focados em streaming e video on demand (vod)
* Projeto Uportal ( e-commerce );
* Integração entre os projetos existentes com forma de pagamento unificada pelo Uportal;
* Projeto Content Delivery Network (media center para empresas de filmes);
* Projeto de Gestão Empresarial em RIA (ERP);
* Projeto Enterprise Information Portal, voltado a gestão de mídias físicas e sua distribuição para locadoras;
* Projeto MMA – Media Manager v1 e v2;
```

**2005/2006 – Navita**
```
Papel: Adobe Coldfusion Developer Pleno
Projetos para VR Beneficios
* Projeto do portal VR (Desenvolvimento / Manutenção / Alterações Sybase);
* Migração de ambientes internos de desenvolvimento e homologação para o portal; 
* Implementação do projeto de EJB no novo portal VR;
* Projeto de Clurster com WebSphere (VR);
```

**2003/2005 - PróWeb Soluções**
```
Papel: Estagiário e Desenvolvedor Web Jr
Projetos para Volkswagem, FIAT, Chevrolet, Bosch and Phillips.
* Programação em websites;
* Programação de banco de dados usando a linguagem SQL, SQL PLUS;
* Auxilio técnico no desenvolvimento de Projetos;
* Arquitetura de Banco de Dados (SQL Server, DBDesigner, mySQL, Oracle 8i); 
* Administração de Banco de Dados; - Manutenção de sistemas legados
* Migração de sistemas legados para tecnologia CFMX 7
* Programação ActionScript integrada ao CFMX7;
* Administração servidor CFMX 7, junto ao sandbox security;
```

#### Cursos
**Machine Learning**
```
 Universidade de Stanford por Coursera
 Status: Em andamento
```  

**Machine Learning e Deep Learning Course**
```
 CETAX Consulting
 Status: Completo em 10/2017
```  

**Google Adwords Partners at Google**
```
 Google Camp
 Status: Completo em 10/2015 and 06/2016
```  

#### Certificações
- Adobe Certified Developer ColdFusion MX 7;
- Google Adwords Fundamentos Pesquisa;
- Google Adwords Pesquisa Avançada;
- Google Adwords Youtube – Publicidade em vídeo;

#### Linguagens de programação e ferramentas
 -  **PHP:** Utilizo desde 2012, principalmente com o Framework Laravel para aplicações de clientes e para junto ao Wordpress para sites. Com Laravel considero um stack bem completo para se iniciar projetos onde o escopo é bem amplo.

 -  **Python:** Utilizo desde o segundo semestre de 2017, inicialmente como estudo e em 2018 como ferramenta para realizar levantamento de insights (libs numpy e pandas) e reconhecimento de imagem que me auxiliou a criar um produto que reduziu o risco de fraudes na insurtech Planetun Services;

 -  **NodeJS:** Inicio de estudo em 2018 para aumento de performance em uso de APIs e distribuição na arquitetura de micro-serviços;

 -  **linguagem-oculta-que-só-você-conhece** Coldfusion, linguagem que está sumindo do mercado de trabalho (apenas manutenção de código legado), porem fui especialista durante alguns anos...tem sua base em Java com orientação a objetos, utiliza JVM e é uma linguagem de script. 

 -  **MySQL / SQL Server / PostgreSQL** Utilizo desde 2006, com mais ênfase as duas primeiras.

 -  **noSQL** Atualmente estudando MongoDB

 -  Conhecimentos básicos: **Java**, **.Net**

## Idiomas
  * Português (nativo).
  * Inglês (técnico avançado);
  * Espanhol (intermediário);
  * Francês (básico);

## Seção Extra, diga o que você quiser
 Atuando há mais de 10 anos como Full Stack Developer, com ênfase nas ferramentas da Adobe. Atualmente estudando Data Science, análise de modelos preditivos com Machine Learning e reconhecimento/classificação de imagens através de Deep Learning.

**Comment by zanaca** [comment]
Opa,  dá uma olhada nas nossas vagas no https://hurb.gupy.io/!
